### ISSUE TITLE
Decimal digit

### ISSUE THREAD

**Issue by SpiringLemming** [hibiyasleep/kagerou#11]
Hello!
First thank you for your amazing work!
I have personally this issue: on the miniparse I have the decimal always .00
I set on the config pane to have 2 digits but the parser always show only integer numbers.
Is not a big issue but maybe a bug.
I am using the last ACT (3.3.0 release 254) and Overlay Plugin 0.3.3.11
My OS is W10 x64
Let me know if you need more info or logs
Thank you
SpiringLemming

**Comment by hibiyasleep** [comment]
It's because of locale differencies, which use `,` instead of `.` to represent decimals. should fixed with 66eb62188a4d5f6e30d3318ebc39b49356e2d26f (v0.6.4).
