### ISSUE TITLE
Blue Mage

### ISSUE THREAD

**Issue by ripps818** [hibiyasleep/kagerou#112]
Blue Mage classes don't show up in the overlay at all. My chocobo, and all other classes appear, but not Blu.

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/51382134-51cdec80-1b59-11e9-8193-7843f8d2fdcb.png)
BLU should appear (at least) like this; however I don't have an account to test it. does BLU appears correctly in ACT itself?

**Comment by ripps818** [comment]
I just checked, and yes, I do show up in ACT itself when attacking a Striking Dummy, but the overlay remains blank.

**Comment by hibiyasleep** [comment]
Can you post contents copied by 'Copy Encounter Data' button (in OverlayPlugin) here?

**Comment by ripps818** [comment]
[overlay_update-variables.txt](https://github.com/hibiyasleep/kagerou/files/2776279/overlay_update-variables.txt)

**Comment by hibiyasleep** [comment]
this was problem - ACT plugin doesn't set job field for BLU.
```js
    // ...
      "Last60DPS": "20",
      "Job": "",
      "ParryPct": "0%",
    // ...
```

Try turn off **Settings > More > Class/Job is empty**.

**Comment by ripps818** [comment]
that fixed it, thanks
