### ISSUE TITLE
Hotlinking overlay results in BrowserError -330

### ISSUE THREAD

**Issue by Livelypower** [hibiyasleep/kagerou#115]
![image](https://user-images.githubusercontent.com/34190721/56077987-e6f02280-5de2-11e9-8c22-390018822914.png)

**Comment by Livelypower** [comment]
Duplicate entry of [this issue, but fix provied doesn't work anymore]( https://github.com/hibiyasleep/kagerou/issues/86)

**Comment by PhonFawn** [comment]
I've got the same error I thought at first I didn't have the newest version of the overlay plugin installed but I updated that and it still load with the same error.

**Comment by hibiyasleep** [comment]
This is basically issue of old version of Chrome (45), which is used by OverlayPlugin. sometimes this version of chrome failing to decodes gzipped data. i'll try to fix configuration of my server.

**Comment by PhonFawn** [comment]
@Livelypower A friend of mine gave me a fix just take off the s from the https:// and it fixes it at least it did for me

**Comment by Livelypower** [comment]
> @Livelypower A friend of mine gave me a fix just take off the s from the https:// and it fixes it at least it did for me

That still didn't do the trick for me

**Comment by PhonFawn** [comment]
rip

**Comment by Livelypower** [comment]
I've been trying to fix this, but reinstalling OverlayPlugin did nothing, anyone have any other ideas?

**Comment by Livelypower** [comment]
Solution: Complete ACT reinstall.

Appearantly some config files remain if you only uninstall OverlayPlugin which screws things over.
Make sure to uninstall ACT and remove all ACT config files.
