### ISSUE TITLE
Damage Breakdown

### ISSUE THREAD

**Issue by Neithis** [hibiyasleep/kagerou#119]
Hi there,

Is there an option to clock or hover over a persons names to show a skill damage breakdown on an encounter?

So say I click on my name it will show a breakdown of what dps/damage each ability done.

Example:

Neithis (DRG) - 6K DPS
Full Thrust - 23% (whatever 23% of 6K is)

(proper example from Recount addon from WoW)
http://prntscr.com/nmuwfd

**Comment by JPBetley** [comment]
Not within the overlay, no. This information is available within ACT itself, but most prefer to upload their ACT logs to https://www.fflogs.com/. That site does very good breakdowns of all the details in your fights.

**Comment by hibiyasleep** [comment]
OverlayPlugin don't provide detailed data for players, while ACT holding it. making it as overlay is another level (= make ACT plugin) of problem. ;(
