### ISSUE TITLE
Wrong date in 0.7.25 release

### ISSUE THREAD

**Issue by Fank** [hibiyasleep/kagerou#124]
![image](https://user-images.githubusercontent.com/1900106/60398784-a2139680-9b5c-11e9-9145-ac8425ca3b03.png)

today is 30 :D

**Comment by hibiyasleep** [comment]
oh wat

**Comment by hibiyasleep** [comment]
<img width="233" alt="image" src="https://user-images.githubusercontent.com/5380174/60399240-a65fa400-9b9c-11e9-86ef-b2e28e478b84.png">

Fixed for GMT+9. thanks!!
