### ISSUE TITLE
Should not merge combatants with correct (non-pet) job

### ISSUE THREAD

**Issue by Yamoto07** [hibiyasleep/kagerou#125]
When you're running a dungeon using the trust system, ACT reads your party members as pets "Minfilia (Your Name)" etc. and shows each one in the main ACT window separately. However, the overlay combines them all into one "pet" since they have the same (Your Name), or if you put your character name in the "Pet merging" option in settings, it all combines into your own dps.

**Comment by hibiyasleep** [comment]
Does they have a 'Job' value in ACT's main table? if then, I'll add an exception for pet merging process.

ps: I don't have Shadowbringers expansion, so please make sure story not be spoiled if you're going to upload other screenshots etc.

**Comment by Yamoto07** [comment]
![image](https://user-images.githubusercontent.com/30032371/60471829-e7eb6000-9c2b-11e9-83ba-c39b5262aeac.png)
![image](https://user-images.githubusercontent.com/30032371/60471833-ee79d780-9c2b-11e9-8489-12d405a3983e.png)
It seems they do have "Job" values.

**Comment by hibiyasleep** [comment]
Yup, checked. thanks!

**Comment by hibiyasleep** [comment]
Fixed by ef9b7ed07841ce24b79946671dba35455dd1e6cc.
