### ISSUE TITLE
Overlay broken in-game

### ISSUE THREAD

**Issue by ThisRiceEater** [hibiyasleep/kagerou#127]
The overlay seems to have unpacked itself.

Image of the overlay in-game.
![VJnm3Ycjy4](https://user-images.githubusercontent.com/52454596/60512537-23fbef00-9d18-11e9-8f5a-7243928b1256.png)

I have no errors showing on my end.
![Advanced_Combat_Tracker_JRD8CnDUmO](https://user-images.githubusercontent.com/52454596/60512550-2bbb9380-9d18-11e9-9823-9a4958ac4cf7.png)

**Comment by hibiyasleep** [comment]
Please try `Reload Overlay` few times. if it doesn't solve a problem, try deleting folder named `cache`, which can be found in ACT installation folder (with this method setting will be lost).

**Comment by ThisRiceEater** [comment]
Deleting 'Cache' fixed it.
