### ISSUE TITLE
Inactive when moving cursor away to top, and option to minimize window to bottom?

### ISSUE THREAD

**Issue by nijow90** [hibiyasleep/kagerou#13]
Hey, I really love your Overlay but  these 2 things that are bugging me a little, is there a way to change it or rather make it an option in the settings?

Here is what I mean
https://www.youtube.com/watch?v=Wi9rHf-iC1Q

**Comment by hibiyasleep** [comment]
This is known problem, which occured by OverlayPlugin doesn't report "cursor leaved your window!" to overlays.

**Comment by hibiyasleep** [comment]
Fixed by 5ee9ecd41c083bebee7e190a4f07d2729a0727b0 which included in 0.6.14.
