### ISSUE TITLE
Kagerou failed to load on web.

### ISSUE THREAD

**Issue by mactassio** [hibiyasleep/kagerou#132]
I'm trying to follow this tutorial to get kagerou to work with OBS
https://www.youtube.com/watch?v=v2UnDCkK7dU

But (even though I use the ingame overlay just fine) the web version of the overlay displays this screen

https://i.imgur.com/vyiO7Rp.png

What might it be?

**Comment by hibiyasleep** [comment]
Don't use URL from ACTWebSocket `127.0.0.1:10501`, it breaks everything completely. use `http://kagerou.hibiya.moe/overlay?HOST_PORT=ws://localhost:10501`.
