### ISSUE TITLE
I see that this was an issue before but... my ACT is picking up all the damage but nothing is showing up on Kagerou

### ISSUE THREAD

**Issue by MinnelMimi** [hibiyasleep/kagerou#137]
As the title states, everything is picked up on the ACT itself but nothing is showing up on the Kagerou overlay. I just downloaded the ACT today so everything should be nice and up-to-date.

**Comment by hibiyasleep** [comment]
other overlays works fine? that seems overlayplugin's issue...

**Comment by MinnelMimi** [comment]
The basic overlay works fine. ( the one you get when you download act) Anyway to fix this problem? Should I just uninstall everything than reinstall?

**Comment by hibiyasleep** [comment]
hmm can you capture OverlayPlugin tab, with kagerou selected?
