### ISSUE TITLE
Getting a null reference exception

### ISSUE THREAD

**Issue by axemtitanium** [hibiyasleep/kagerou#139]
7/29/2019 4:00:15 AM: Error: Mini Parse: XivWindowWatcher: System.NullReferenceException: Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__11(Object o, ElapsedEventArgs e)

The overlay won't appear at all. Clicking any of the three buttons also throws an exception.

**Comment by hibiyasleep** [comment]
Check you've installed correct OverlayPlugin, according to your system, 32- or 64-bit.

**Comment by axemtitanium** [comment]
Thanks that fixed it. Noob mistake!
