### ISSUE TITLE
Any way to display mob deaths?

### ISSUE THREAD

**Issue by de-gene-rate** [hibiyasleep/kagerou#146]
Was wondering if theres anyway to make the overlay display mob deaths. I know act already tracks them cause the death counter keeps track of how many mobs have died, i just dont know how to get the overlay to display it.

Something simple like:

Mob Name         Deaths

**Comment by hibiyasleep** [comment]
those data are not provided by OverlayPlugin, therefore kagerou can't access to them. I would make it in other project rather than integrating into kagerou...seems kinda other type of feature.
