### ISSUE TITLE
Request: RDPS display in header & Option to remove the footer

### ISSUE THREAD

**Issue by WhizardKitty** [hibiyasleep/kagerou#149]
Is it possible to provide the option to remove the footer element and allow the RDPS to display in the header with encounter time and name?
Also is it possible to automatically use 24 tab layout when in alliance raid content?

**Comment by DerpyMoa** [comment]
I would like this too please

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/70871340-b1d74800-1fe1-11ea-8439-f6d35b552352.png)
![image](https://user-images.githubusercontent.com/5380174/70871341-b56acf00-1fe1-11ea-82c0-b8b006dceb3c.png)

both will be included in next update.

there's only concern is... should I fit table into contents, in case of footer hidden?
current icons and bar graphs didn't excepted bottom end to be opened so it looks to close to edge of overlay (see rdm icon), so I would little bottom padding to hide those.

**Comment by WhizardKitty** [comment]
If a little padding could fix that I don't see an issue really, personally I use line height turned up so it is coloured bars and don't see the icon being to big of a problem as long as it doesn't intrude onto the next line
Also considering it only being an issue when it's closed i dont see it being something to worry about much
Thank you for adding this feature and updating me as it is being worked on. Look forward to using it when it is updated and thank you for your work :)

**Comment by WhizardKitty** [comment]
Looks amazing thank you for the update. How do i get the rdps to show at the top the, got the footer to be removed but rdps not showing

**Comment by hibiyasleep** [comment]
it'll released with version number of `0.8.2`. I'm keep working but there's many changes and tiny spare times. sorry for late follow-up ;(

**Comment by hibiyasleep** [comment]
Closed by 1712c452b030c2342921a7a264260308545c8267.
