### ISSUE TITLE
Icons are broken with latest update

### ISSUE THREAD

**Issue by raiku314** [hibiyasleep/kagerou#15]
So with this update icons are broken completely. For most classes the original icon of the profession is displayed instead of a job(i.e. Rogue instead of Ninja). In case of astrologian fisher icon is displayed, and SMN gets the Archer icon.

**Comment by nijow90** [comment]
check the date, mate

**Comment by ClassyMicrochu** [comment]
I thought this was just hilarious seeing icons being  mixed, and matched. Indeed such a great prank for a certan day of the month ;)

**Comment by hibiyasleep** [comment]
See https://github.com/hibiyasleep/kagerou/commit/14e5c0907ff8d3d83505b5fa13ec0c11b9996af6#diff-13a7c14c3532f2ee373c367befbff6caR240; read here capitalized letters. ALL things will go back as of `00:00 2 Apr`.

Well there were *real* bug, I mapped SMN and ARC. lol
