### ISSUE TITLE
Change color for personal DPS bar

### ISSUE THREAD

**Issue by Braiken** [hibiyasleep/kagerou#158]
Hello,

I would like to know if it's possible to change the color of my and only my Dps/Hps bar, even if I change job, on kagerou.
I strated checking the devtools but i'm not a dev and don't know HTML neither CSS, I found where each line of dps are created and found where colors are set up but don't really know what to do from now. Tried to look up for thing on internet but I don't really know what to ask so I'm posting here.
I'll keep searching on internet.

Hope you are doing good.

PS : my request is not urgent and could be solved if I found the right website, don't bother reply if you are busy.

**Comment by hibiyasleep** [comment]
it's possible with custom CSS: replace `#ff0000` with color code you want.
```css
#table .me .gauge { backgroud-color: #ff0000 !important }
```

**Comment by Braiken** [comment]
I found a way to make the same effect few minutes ago but only saw your message now plus my method was way more long to make since I had to change the color for each class. I'll use your code much beautiful than mine. 

Thanks a lot for your answer
