### ISSUE TITLE
Separate thousands place with a comma

### ISSUE THREAD

**Issue by krazyito65** [hibiyasleep/kagerou#159]
Is there anyway you could add an option to separate the numbers with commas for stuff above 1000? I feel like it makes it much easier to read.

**Comment by Sundava** [comment]
In the same spirit, would it be possible to add the option to shorten values using K suffix, like MopiMopi does ?
ACT's "Simplify numbers" option does not do anything for Kagerou

**Comment by hibiyasleep** [comment]
'Smaller font for under-k digit for dps' was added with the purpose of actually this. (I don't like commas, sorry)

and... 'abbreviate numbers' option was added at 50a993c279756e98b9f918106cb4c1c5ac916a9d and version v0.8.6.

**Comment by Sundava** [comment]
Is it possible to extend this option to the total damage/healing columns too ?
