### ISSUE TITLE
Issue with table footer when Outer Margin is set to 0 in Style

### ISSUE THREAD

**Issue by yuchingwang** [hibiyasleep/kagerou#16]
When Outer Margin is set to 0, the footer height is too low, resulting in a small amount of the footer text getting cut off.

Also, advise changing the load order for css. Currently, custom CSS is loaded first, so very little control is actually provided from this feature.

**Comment by hibiyasleep** [comment]
Thanks for report, fixing it.

**Comment by hibiyasleep** [comment]
Currently normal CSS are loaded asynchronously, but custom CSS isn't. this makes fixing it harder, so I'll fix this later.

**Comment by hibiyasleep** [comment]
Fixed in v0.6.18-033.987.
