### ISSUE TITLE
Parsing issues

### ISSUE THREAD

**Issue by ianmrz** [hibiyasleep/kagerou#161]
Since new update on 6/16/2020 ACT has not been uploading FFXIV data for parsing but able to call triggers for fights? Any1 else have issues with this? In the kagerou overlay it just says tears of proof masquerade

**Comment by hibiyasleep** [comment]
there weren't changed anything (`v0.8.3`, `v0.8.4`), I can't determine anything from this case. try deleting `OverlayPluginCache` in your ACT (or `Plugin`) directory, to flush cache?

**Comment by hibiyasleep** [comment]
ps: please check `Main` tab of ACT, there should combats are logged (ensure it has correct dps parsing) if everything works well except kagerou. if not, it's more likely problem with FFXIV_ACT_Plugin or windows firewall etc.
