### ISSUE TITLE
NaN in footer RDPS

### ISSUE THREAD

**Issue by piotrp** [hibiyasleep/kagerou#165]
![obraz](https://user-images.githubusercontent.com/1409807/118174109-b39f7800-b42e-11eb-9236-b0982c75cf1e.png)

I reset settings just in case it's some configuration issue, but it didn't help.

**Comment by Peanut84** [comment]
Same issue here, did you solved it?

**Comment by hibiyasleep** [comment]
Might be fixed by https://github.com/hibiyasleep/kagerou/commit/975a1b6129698aaeaf11664cbd2a717d749e65ad (or not, since I couldn't figure out what's wrong)

**Comment by piotrp** [comment]
Thanks, that fixed it
