### ISSUE TITLE
Target Bar / Target of Target / Focus Target overlay setting not saving

### ISSUE THREAD

**Issue by Asger91** [hibiyasleep/kagerou#171]
I tried it multiple times now but when I change the setting for these overlays and play it is all good and well.
But when I restart ACT the setting are completely gone and reverted back to before.

I tried to make a backup of the plugins as well as the config file, copied the backup back again, reloaded the overlay but it still is reverted.
I have the backup folder, even if I import one of the backups it's still the same nothing is saved from the changes I made.

24:00
Now I tried reinstalling the plugin and restarting ACT now I get the error that the file could not be loaded...

![Capture](https://user-images.githubusercontent.com/38844325/124520300-4be12a00-ddec-11eb-8834-08bc4ab9e51e.JPG)

**Comment by hibiyasleep** [comment]
remove current OverlayPlugin, then try [this version of OverlayPlugin](http://github.com/ngld/OverlayPlugin) instead. this version can also be downloaded by _ACT -> Plugins -> Get Plugins_.

**Comment by Asger91** [comment]
Yeah that version doesn't work sadly.
I got it from your link and again from ACT plugins like before but both don't save or even start up properly

**Comment by hibiyasleep** [comment]
🤔  does any other error message appeared?

however, this is actually a problem of setting up ACT itself, not kagerou. I suggest to get help around like [FFXIV_ACT discord](https://discord.gg/5h7EU9YW) or somewhere else, since what can I help here is very limited over those.
