### ISSUE TITLE
ContentDecodingFailed

### ISSUE THREAD

**Issue by justin-slattery** [hibiyasleep/kagerou#179]
Apologies if this is a common issue, but I'm a relatively new user, and my meters haven't been working for the past couple days. When trying to load, the following error appears in the logs:

[9/9/2021 2:18:57 PM] Error: DPS Meter: BrowserError: ContentDecodingFailed, ERR_CONTENT_DECODING_FAILED, https://hibiyasleep.github.io/kagerou/overlay/

**Comment by hibiyasleep** [comment]
it's fault GitHub server or OverlayPlugin, rather than kagerou itself. if this issue persists, try change URL as `https://idyllshi.re/kagerou/overlay`, this might be help.
