### ISSUE TITLE
ACT Crashes

### ISSUE THREAD

**Issue by TomSchillemans** [hibiyasleep/kagerou#19]
ACT crashes with I enable this plugin and also, the settings pane stays blank.
After ACT crashes, the settings aren't saved when i restart it.

**Comment by hibiyasleep** [comment]
It's the problem more related with OverlayPlugin, please open issue to [hibiyasleep/OverlayPlugin](https://github.com/hibiyasleep/OverlayPlugin) with detailed error information.

**Comment by TomSchillemans** [comment]
Still leaves me with a couple of questions. OverlayPluggin works perfectly with other skins. And also why would the settings screen stay blank if it was the OverlayPluggin's fault?    
  
  
  
  
  

  
  
>

**Comment by hibiyasleep** [comment]
OverlayPlugin supposed to not to crash, even buggy skin loaded, because it's a web browser. Plugin crash means that plugin failed to do it's function.

However I also maintain OverlayPlugin now, I may help to solve this issue with full crash log.
