### ISSUE TITLE
How do I update Kagerou in ACT?

### ISSUE THREAD

**Issue by miller0929** [hibiyasleep/kagerou#193]
Hi, I'm new to FF14 and I'm using ACT and Kagerou. The game had a new patch today. Then, my overlay doesn't show dps anymore. Do I need to wait for you to update Kagerou? How long does it usually take you? Thanks.

**Comment by Sundava** [comment]
Kagerou itself doesn't need to be updated when a patch hits, as it relies on the ACT FFXIV plugin.
When the ACT plugin is updated, a popup will appear when launching ACT. It generally takes one or two days at most.

You can join the [ACT Discord](https://discord.gg/9tHJ7s2P3r) or the [FFXIV_ACT_Plugin](https://github.com/ravahn/FFXIV_ACT_Plugin) repo if you want to get the latest information, but the only thing to do is to wait a bit until ravahn patches it.
