### ISSUE TITLE
Need Help With a Few Lines of Code

### ISSUE THREAD

**Issue by Brightbrown** [hibiyasleep/kagerou#194]
Asked this is another thread then saw it had been closed... so here's a fresh request. Took the boat from Stormwind to Limsa and ain't looking back. The Kagerou overlay is exactly what I was looking for but I can't figure out how to do 2 smallish things to the UI. Think they may mean a few lines of code that I couldn't possibly come up with myself, so ask kindly if someone could...

I want to reduce the size of the text in the top menu/nav bar. Would not  mind if it was the same font/size as the listings were. Secondly, I'd like to get rid of the zone listing (that appears in gray text) in said title bar. I even went looking through settings to see if that gray color was specified so I could make it back, thus hiding it).

I'd be pretty grateful if someone did me a solid (as we used to say back in my time!).

**Comment by hibiyasleep** [comment]
You would use 'Narrower Top navigation bar' menu first. if you need small font size still, custom CSS should be used: 
```css
.history { font-size: 0.75rem }
```
this will result this:
![image](https://user-images.githubusercontent.com/5380174/159159818-0d5dce0e-f2e6-479d-9486-66f1f9a29e03.png)

You can remove location text completely if you don't use header, by enabling 'Use header, for elements instead' and disable all footer elements. or you're using footer elements, then by custom CSS:
```css
#history-region { opacity: 0 }
```

**Comment by Brightbrown** [comment]
Wow, can't thank you enough... the font size worked like a charm. Took a wee bit of fussing, but I got the region gone... I am a happy camper.
