### ISSUE TITLE
Config will be reset everytime

### ISSUE THREAD

**Issue by Tythla** [hibiyasleep/kagerou#196]
The config of UI zoom and layout was reset everytime I started ACT. Everything else works just fine. It's 0.8.14 Chinese version.

**Comment by hibiyasleep** [comment]
it's OverlayPlugin issue, I have no things that I can solve at my side. Install latest OverlayPlugin from [here](https://github.com/ngld/overlayplugin), and make sure `OverlayPluginCache` folder persists.
