### ISSUE TITLE
Certs are expired for secure url

### ISSUE THREAD

**Issue by seathasky** [hibiyasleep/kagerou#197]
https://kagerou.hibiya.moe/overlay/
https://idyllshi.re/kagerou/overlay/

Certs are expired!

![Screen Shot 2022-06-17 at 10 50 33 PM](https://user-images.githubusercontent.com/17598024/174419814-8ed5f941-965b-4daa-8b72-00c49b8aa1cc.png)
![Screen Shot 2022-06-17 at 10 51 51 PM](https://user-images.githubusercontent.com/17598024/174419876-519dd14b-1f55-4a94-8d54-9371e47f84f8.png)

**Comment by hibiyasleep** [comment]
I'm suck at this, sorry! fixed!!
