### ISSUE TITLE
Request: Quick guide for building the main HTML

### ISSUE THREAD

**Issue by veltall** [hibiyasleep/kagerou#2]
Hey kagerou! Thanks for the awesome ACT overlay skin for FFXIV!

I've been able to use your overlay by sourcing the html hosted online at `https://hibiyasleep.github.io/kagerou/overlay`. However I cannot make changes to parts of the overlay itself that are not configurable in the settings (table headers in Korean, for example) as all the files are server-side.

Would you mind helping me learn how to create the source `.html` for the overlay, so I can modify it for personal use?

**Comment by hibiyasleep** [comment]
You can fork this repository and configure gh-pages, or simply download this repository and use locally.

However, localization is in progress, please wait for v0.5.0! (will soon, maybe hour?)

**Comment by hibiyasleep** [comment]
Translation is done, and you can use it now!
