### ISSUE TITLE
Numbers not showing, as well as buttons sometimes not showing

### ISSUE THREAD

**Issue by nmleb3s** [hibiyasleep/kagerou#21]
The overlay usually does not show anything but the grey rows where the text should show up when I open it. When it starts parsing, only the color bar shows up, not the job symbol or the person's name or dps. The settings menu also is not functioning.

**Comment by hibiyasleep** [comment]
It's really curious bug, Is width of bar correct? or random or 100% filled?

On overlay config, there's a button labeled 'Copy Update Variables'. press it _at the moment_ of this happens, and please reply here.

**Comment by nmleb3s** [comment]
{}
This is all I get after pressing the copy update variables button

**Comment by nmleb3s** [comment]
{"Encounter": {"n":"\n","t":"\t","title":"Encounter","duration":"00:00","DURATION":"0","damage":"1018","damage-m":"0.00","DAMAGE-k":"1","DAMAGE-m":"0","DAMAGE-b":"0","dps":"∞","DPS":"∞","DPS-k":"∞","DPS-m":"DPS-m","encdps":"∞","ENCDPS":"∞","ENCDPS-k":"∞","ENCDPS-m":"∞","hits":"1","crithits":"0","crithit%":"0%","misses":"0","hitfailed":"0","swings":"1","tohit":"100.00","TOHIT":"100","maxhit":"YOU-Throwing Dagger-1,018","MAXHIT":"YOU-1,018","healed":"0","enchps":"---","ENCHPS":"---","ENCHPS-k":"---","ENCHPS-m":"---","heals":"0","critheals":"0","critheal%":"---","cures":"0","maxheal":"","MAXHEAL":"","maxhealward":"","MAXHEALWARD":"","damagetaken":"0","healstaken":"0","powerdrain":"0","powerheal":"0","kills":"0","deaths":"0","CurrentZoneName":"The Dravanian Hinterlands","Last10DPS":"∞","Last30DPS":"∞","Last60DPS":"∞"},"Combatant": {"YOU": {"n":"\n","t":"\t","name":"YOU","duration":"00:00","DURATION":"0","damage":"1018","damage-m":"0.00","damage-b":"0.00","DAMAGE-k":"1","DAMAGE-m":"0","DAMAGE-b":"0","damage%":"100%","dps":"∞","DPS":"∞","DPS-k":"∞","DPS-m":"∞","encdps":"∞","ENCDPS":"∞","ENCDPS-k":"∞","ENCDPS-m":"∞","hits":"1","crithits":"0","crithit%":"0%","crittypes":"-","misses":"0","hitfailed":"0","swings":"1","tohit":"100.00","TOHIT":"100","maxhit":"Throwing Dagger-1,018","MAXHIT":"1,018","healed":"0","healed%":"--","enchps":"---","ENCHPS":"---","ENCHPS-k":"---","ENCHPS-m":"---","critheals":"0","critheal%":"0%","heals":"0","cures":"0","maxheal":"","MAXHEAL":"","maxhealward":"","MAXHEALWARD":"","damagetaken":"0","healstaken":"0","powerdrain":"0","powerheal":"0","kills":"0","deaths":"0","threatstr":"+(0)0/-(0)0","threatdelta":"0","NAME3":"YOU","NAME4":"YOU","NAME5":"YOU","NAME6":"YOU","NAME7":"YOU","NAME8":"YOU","NAME9":"YOU","NAME10":"YOU","NAME11":"YOU","NAME12":"YOU","NAME13":"YOU","NAME14":"YOU","NAME15":"YOU","Last10DPS":"∞","Last30DPS":"∞","Last60DPS":"∞","Job":"Nin","ParryPct":"0%","BlockPct":"0%","IncToHit":"---","OverHealPct":"0%"}},"isActive": true}
This is after one hit on a striking dummy.
![problematic kagerou overlay](https://cloud.githubusercontent.com/assets/28469674/25774438/905f42ec-325c-11e7-821f-44da58366473.PNG)
This is what the overlay looks like

**Comment by hibiyasleep** [comment]
Nothing wrong with ACT's data... does resetting all settings work?

**Comment by nmleb3s** [comment]
The problem with resetting all settings is that the settings menu also glitches so I can't interact with it.
![problematic kagerou settings](https://cloud.githubusercontent.com/assets/28469674/25790587/ed07aa30-3387-11e7-88d7-71da3a5831b3.PNG)
Here is what the settings menu looks like.

**Comment by hibiyasleep** [comment]
This is unbelievable issue, might related to OverlayPlugin renderer......

Which version of OverlayPlugin are you using?

**Comment by nmleb3s** [comment]
I'm using 0.3.3.11

**Comment by hibiyasleep** [comment]
ok, I'll file this as OverlayPlugin's bug, thanks for report.

Below is possible option to solve this, but may or may not work.

* Try reinstall OverlayPlugin, latest version 0.3.3.12 may work.
* Click 'Open DevTools', and paste this into console and press enter:
```js
config.set('style.body-font','Segoe UI');config.save();location.reload()
```

**Comment by nmleb3s** [comment]
It was fixed after I entered that line into the console. Thank you very much.

**Comment by nmleb3s** [comment]
Settings menu was fixed after updating OverlayPlugin.

**Comment by nmleb3s** [comment]
Settings menu now sometimes shows up properly after updating OverlayPlugin.

**Comment by hibiyasleep** [comment]
I guess... it's a font problem. by default, kagerou uses this font set, top to bottom, if exists:

* **Roboto** - Webfont, which loaded from itself.
* **Segoe UI** - Default font since Windows Vista.
* **Meiryo UI** (メイリオ) - Windows default japanese font.
* **Source Han Sans** - Ignored if doesn't exists.
* **MalgunGotinc** (맑은 고딕) - Windows default korean font.
* **sans-serif** - stands of 'browser default font', usually **Arial**.

So please check your computer, make sure this fonts are _not broken_ or _doesn't exists_. nonexists are OK.

**Comment by nmleb3s** [comment]
Roboto, Meiryo, and Source Han Sans do not show up in my installed fonts.

**Comment by hibiyasleep** [comment]
Got it, I'll check later.
