### ISSUE TITLE
Settings not saved, plugin version 0.3.3.11

### ISSUE THREAD

**Issue by tguegan** [hibiyasleep/kagerou#23]
Hey, I've just installed your Overlay but each time I close ACT my settings are reset... I'm using the OverlayPlugin version 0.3.3.11 and I've tried with the x64 and x86.

![overlayplugin](https://cloud.githubusercontent.com/assets/22313632/25863245/63fb20a4-34eb-11e7-83d9-3c1dc5834eee.JPG)

Otherwise the Overlay is working flawlessly.

**Comment by hibiyasleep** [comment]
How do you start ACT? via shortcut?

**Comment by tguegan** [comment]
Yes, as admin

**Comment by hibiyasleep** [comment]
Right click on shortcut, and please make sure "Start in:" configured as same folder as where ACT.exe lives.

**Comment by tguegan** [comment]
Still not working, each time I reload ACT, the overlay come back to default settings

**Comment by Maxxgold** [comment]
Your antivirus or user level is causing your problems. Also, if you downloaded the setup version, then try the zip file version.

**Comment by hibiyasleep** [comment]
You should get a folder named `cache` where "Start in" specified, containing files like this:

![image](https://cloud.githubusercontent.com/assets/5380174/26013733/b54dd1c6-3794-11e7-9a0b-a0d193af31d1.png)
