### ISSUE TITLE
ACT crashes every time

### ISSUE THREAD

**Issue by BanaKori** [hibiyasleep/kagerou#25]
Every time I put in the URL for this overlay, it always tells me "something went wrong" and gives me the options of "Retry, Restart, Settings" No matter what I click, or even exiting from the settings menu, will instantly crash my parser and force me to restart.

I'm really not sure what to do anymore, this is extremely frustrating.

**Comment by hibiyasleep** [comment]
kagerou can't make ACT crash, and it's impossible. if it did, it's ACT or OverlayPlugin's bug. Please make sure:

* your OverlayPlugin is latest (is 0.3.3.12)
* ACT is running as admin

and, post ACT error log here please, I'll help you with what I can.

**Comment by BanaKori** [comment]
Sure, no problem. I'll see what I can do.

**Comment by BanaKori** [comment]
Thank you! I just had to update to the latest version and be sure the other directories were pointing the right ways. I put the OverlayPlugin folder in the same spot as ACT. Thank you so much!
