### ISSUE TITLE
New classes for 4.0 showing up as black color 

### ISSUE THREAD

**Issue by keberos** [hibiyasleep/kagerou#28]
The bars are showing up as black for samurai and red mage instead of the yellow and red the config suggest. Not a huge issue since otherwise the job icons are working but I thought I would report the issue. Thanks for your work.

**Comment by Ytilee** [comment]
Just wanted to confirm this observation. Even trying to change the color in the config menu doesn't change it.

**Comment by hibiyasleep** [comment]
It's typo, will fixed soon.
