### ISSUE TITLE
Fullscreen Support

### ISSUE THREAD

**Issue by keberos** [hibiyasleep/kagerou#29]
Enhancement request if not already supported. This is the best overlay I've seen. Is there a way to get it to work with fullscreen mode in game? So that it is still shown on same monitor even if fullscreen. Thank you.

**Comment by hibiyasleep** [comment]
Since OverlayPlugin doesn't support fullscreen injection, it's unable to implement. [This one](https://github.com/Soreepeong/DPSViewer) doesn't support SB yet, but also works in fullscreen mode.
