### ISSUE TITLE
Not functioning

### ISSUE THREAD

**Issue by Gel-Banana** [hibiyasleep/kagerou#3]
I'm unable to figure out how to fix it.

When i first added it, i had enimity overlay on, which i then deactivated and later deleted, i don't know if that's what caused this issue, but it just won't track anything at all whatsoever.

http://prntscr.com/durp7k

**Comment by veltall** [comment]
Have you tried re-installing everything? Tends to fix most problems, albeit it's a bit inconvenient.

**Comment by hibiyasleep** [comment]
Check ACT itself, does data get updated?

**Comment by veltall** [comment]
Don't forget the Firewall rule if you're setting ACT up from scratch.

**Comment by hibiyasleep** [comment]
Closing due to not enough information.
