### ISSUE TITLE
Include Direct Hit Section for Damage

### ISSUE THREAD

**Issue by dnorthrupva** [hibiyasleep/kagerou#30]
Now that we're re-calculating BiS, etc. Is it possible to get a 'Direct Hit %'? Does the log specify the data properly to parse off of that?

**Comment by hibiyasleep** [comment]
I think this *should* possible, does ACT displays 'Direct Hit' in it's `Main` tab?

see also: https://github.com/hibiyasleep/OverlayPlugin/issues/9

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/27493949-bd3ec47c-5886-11e7-9be3-ad7116e4cdfd.png)

~I hope that 0% is just a bug~

Will included in 0.7.0-pre1, which is coming now.
