### ISSUE TITLE
Max Damage having some bugs.

### ISSUE THREAD

**Issue by yangstur** [hibiyasleep/kagerou#35]
On the max damage tab, its showing skill.alias.skill.(skill name) for everybody's max hitting skill. 
![skill](https://user-images.githubusercontent.com/13777671/27652570-476c7046-5c0a-11e7-91b2-5f50bffded07.png)

**Comment by hibiyasleep** [comment]
fixing now, sorry for inconvience.

**Comment by yangstur** [comment]
thanks for the quick fix!
