### ISSUE TITLE
Uncorrect % of Crit Direct and !!! % 

### ISSUE THREAD

**Issue by makke007** [hibiyasleep/kagerou#37]
Kagerou currently has some bugs with Direct Hits and !!! Hits it seems. I am getting % over 100 dor Direct Hits which is impossible obviously. Same goes for quite high !!! Numbers aswell. Crit seems to be working fine.

Other issue was already Reported with the Name Alias's 

https://puu.sh/wwMdX/7a2c64df75.png

**Comment by hibiyasleep** [comment]
currently FFXIV_ACT_Plugin has problem, since kagerou calculates DH/CDH numbers by (DH・CDH count/hitcount).

See more at: [FFXIV_ACT_Plugin#90](https://github.com/ravahn/FFXIV_ACT_Plugin/issues/90)

**Comment by hibiyasleep** [comment]
Fixed with v1.5.1.5 of FFXIV_ACT_Plugin.
