### ISSUE TITLE
Solo Mode

### ISSUE THREAD

**Issue by alhenti** [hibiyasleep/kagerou#45]
Not exactly an issue, but rather a question.
How can I use Solo Mode? 

I am expecting a window that lists the currently used weaponskills with their respective damage. Similar to ACT "Outgoing Damage" window for "YOU". 

Many thanks!

**Comment by hibiyasleep** [comment]
Solo mode activates by clicking ![image](https://user-images.githubusercontent.com/5380174/27867158-d69a16c8-61d3-11e7-9507-e85f938700eb.png) icon, and displays only YOUr column when activated.

Details about skill usage are not provided by OverlayPlugin, so it's unable to display. sorry :(

![image](https://user-images.githubusercontent.com/5380174/27867148-d01efaac-61d3-11e7-96fe-b760f98d788e.png)
