### ISSUE TITLE
How to change the font color

### ISSUE THREAD

**Issue by Protoffxiv** [hibiyasleep/kagerou#47]
Sorry if this is a silly question but, i'm not sure how to change the color of the font from white. I'm looking for a darker background as the image i'm using is white, so it's a little hard to see. Is there a way to do this?

![image](https://user-images.githubusercontent.com/29964055/27937227-72bac2e6-6283-11e7-8f55-bbc694a0e593.png)

**Comment by hibiyasleep** [comment]
Main color can be changed in `Style > Foreground > Table`, however there's another workaround for this:

* Set text shadow as `0 0 0.25em rgba(0, 0, 0, 1), 0 0 0.25em rgba(0, 0, 0, 1)` - repeat as you need.
* You may apply background 'filter': See [here](http://www.cssfiltergenerator.com) to create value.
