### ISSUE TITLE
Long skill names not fitting in Max column

### ISSUE THREAD

**Issue by veltall** [hibiyasleep/kagerou#5]
I'll try to keep a list of the skill names for reference purposes. These are skills potential to show up as the highest hit:

### PLD
- Royal Authority
- Spirits Within

### WAR
- Fell Cleave
- Butcher's Block

### DRK
- Souleater
- Carve and Spit

### WHM
- Assize
- Stone III

### SCH
- Broil
- Energy Drain

### AST
- Malefic II

### MNK
- The Forbidden Chakra
- Tornado Kick
- Elixir Field

### DRG
- Full Thrust
- Jump
- Dragonfire Dive
- Fang and Claw
- Wheeling Thrust

### NIN
- Trick Attack
- Sneak Attack
- Raiton
- Aeolian Edge

### BRD
- Empyreal Arrow
- Sidewinder

### MCH
- Wildfire
- Clean Shot

### BLM
- Fire IV
- Flare
- Thunder III
- Blizzard IV

### SMN
- Deathflare
- Painflare
- Ruin III
- Aerial Blast
- Earthen Fury
- Inferno

**Comment by hibiyasleep** [comment]
Thanks, ok, 'The Forbidden Chakra' is the problem, got it.

**Comment by hibiyasleep** [comment]
from Rook Autoturret I saw:

* Charged Volley Fire

will replace with 'ChrgdVollyFire', it'll correct?

**Comment by hibiyasleep** [comment]
Partly solved with af49187e187feae317d73fd3112d307042596f36, which replace "The Forbidden Chakra" as "Forb..Chakra".

This feature references [`skill.alias` in langfile](https://github.com/hibiyasleep/kagerou/blob/af49187e187feae317d73fd3112d307042596f36/share/lang/en.json#L250).

**Comment by veltall** [comment]
Rook Autoturret is unlikely to have the strongest hit, so fixing that is only for completionists. I doubt any users will ever notice the problem, much less complain about it.

**Comment by hibiyasleep** [comment]
EN solved, but how about JP skillnames? Do I need to convert it into half-width katakana?

**Comment by hibiyasleep** [comment]
Closing due to inactive.

**Comment by veltall** [comment]
Petition to reopen due to Bard's new skill "Refulgent Arrow" not fitting. There may be new skills that suffer this problem (Samurai's Midare Setsugekka comes to mind).

I'll keep an eye out for these and make a list.
