### ISSUE TITLE
Create 'Ignore Error' flag to overlay

### ISSUE THREAD

**Issue by hibiyasleep** [hibiyasleep/kagerou#51]
🤔

**Comment by super1578** [comment]
I'm having the same issue. Did you make any headway?

**Comment by hibiyasleep** [comment]
what's the issue? `/outdated` redirection appears when kagerou can't run in current browser.

**Comment by super1578** [comment]
![kagerou error](https://user-images.githubusercontent.com/30273927/28365894-037e6f78-6c50-11e7-8f9d-a1dc41152fe6.png)

This is what I get.

**Comment by hibiyasleep** [comment]
Can you capture 'More info' section, at end of page?

**Comment by super1578** [comment]
I got it fixed
