### ISSUE TITLE
DPS stats disappear after few seconds

### ISSUE THREAD

**Issue by perks** [hibiyasleep/kagerou#52]
Latest version seeems to have broken the overlay -- dps will work for a couple seconds before failing with the following error showing in log:

7/16/2017 1:51:10 PM: Info: Kagerou: BrowserConsole: Uncaught ReferenceError: conf is not defined (Source: https://cdn.ravenjs.com/3.15.0/raven.min.js, Line: 2)

**Comment by catlickspoop** [comment]
having exact same since latest version, can still see dps values if use the "24" tab though.

Just the dps tab itself stops showing numbers the moment a second player is involved

**Comment by bcase1o1** [comment]
I found that if you remove the DPS percentage of boss health, then the tab will start working again. Obviously it is not a solution, but i haven't been able to fix the actual problem, nor do i know if i even can. It's probably on hibiyas end.

**Comment by Ytilee** [comment]
Oh I'm sorry, I did just post an issue about that.
After about one hour of testing, I can assure it's everytime someone else than my character is parsed that this bug arises. I did a lot of solo training (about 2h) and the bug never came up.
Also should I remove my issue since it seems covered here ?

**Comment by perks** [comment]
Re #53 of you remove the Dmg % column from the display everything will work as normal

**Comment by hibiyasleep** [comment]
This was fixed by c423afee74535c6bffd7b1e52dc751767b2e8b99, sorry for inconvience ;(

**Comment by perks** [comment]
no worries hibiya, you do great work we love you man
