### ISSUE TITLE
Deal % broken since todays update 0.7.7

### ISSUE THREAD

**Issue by Ergwano** [hibiyasleep/kagerou#53]
Since todays update the "Deal %" is breaking the overlay when more than one person is displayed.
I get the error message and no players are displayed in the overlay:
`16.07.2017 20:44:56: Info: Overlay: BrowserConsole: Uncaught ReferenceError: conf is not defined (Source: https://cdn.ravenjs.com/3.15.0/raven.min.js, Line: 2)`
But when I remove the "Deal %" then everything works fine.

**Comment by hibiyasleep** [comment]
This was fixed by c423afee74535c6bffd7b1e52dc751767b2e8b99, sorry for inconvience ;(
