### ISSUE TITLE
Overlay not displaying data

### ISSUE THREAD

**Issue by HammerBag** [hibiyasleep/kagerou#56]
Overlay won't display any parse data as of July 16, 2017 (was working July 15). Other (locally-saved) overays are displaying the data. Seemed to be able to get data when solo on a striking dummy, but in any kind of party, no data is displaying. Tried in party on a striking dummy. As long as I was hitting solo, data was displaying. As soon as a party member hit the dummy, all data disappeared.

**Comment by MinhOh** [comment]
If you have Total damage % Tick on, turn it off it is giving and error. it says in #52 and #53
