### ISSUE TITLE
Overlay Settings not saving on relaunch.

### ISSUE THREAD

**Issue by Naxthor** [hibiyasleep/kagerou#60]
So I have installed it using the steps shown but when I rebooted my computer today and opened ACT it reverted the overlay to the default and got rid of all my custom settings.

**Comment by hibiyasleep** [comment]
Please make sure your ACT running with latest OverlayPlugin (at least 0.3.3.10), download is [here](https://github.com/hibiyasleep/OverlayPlugin/releases/latest).
