### ISSUE TITLE
Version Mismatch on Redirect/Unsecure Mode

### ISSUE THREAD

**Issue by Griever92** [hibiyasleep/kagerou#61]
Using Kagerou with OBS and ACTWebSocket appears to redirect to an incorrect version of Kagerou.

After adding the following URL to WebSocket Web Skins
`https://hibiyasleep.github.io/kagerou/overlay`

![advanced combat tracker_2017-08-01_05-39-39](https://user-images.githubusercontent.com/7936026/28823644-dd4afa8e-767b-11e7-95a5-64ceaf7073cf.png)

The URL copied from WebSocket, for use in OBS comes back as
`https://hibiyasleep.github.io/kagerou/overlay?HOST_PORT=wss://[::1]:10501/`

However, the URL redirects to
`http://kagerou.hibiya.moe/overlay/?HOST_PORT=wss://[::1]:10501/`

The redirect is still using v0.7.8 (Dead and Seek)
![chrome_2017-08-01_05-42-20](https://user-images.githubusercontent.com/7936026/28823725-3ed57cd4-767c-11e7-8b2f-69cc6ab24aa7.png)

Any attempt to use Kagerou with WebSocket, even when SSL is enabled, results in a redirection to Kagerou's "UNSECURE MODE"

**Comment by hibiyasleep** [comment]
Redirection to insecure `http://kagerou.hibiya.moe`, is temporal solution to CORS policy of browsers which doesn't allow connecting `ws` (not `wss`) from `https`.

version mismatch is just my mistake, I'll setup auto depoly soon on kagerou.hibiya.moe.
