### ISSUE TITLE
Problem with the URL

### ISSUE THREAD

**Issue by Kou4444** [hibiyasleep/kagerou#63]
Hello, wheneever i try to change the Url (https://hibiyasleep.github.io/kagerou/overlay) in the overlayplugin setting i get an error and the whole parser wont show up.
The error i get looks like this : 
Mini Parse: BrowserError : ConnectionReset, , https://hibiyasleep.github.io/kagerou/overlay

Thanks in advance for the help. 
![83](https://user-images.githubusercontent.com/30768514/29001678-850a5094-7a91-11e7-9aed-c80da962a868.PNG)

**Comment by hibiyasleep** [comment]
seems GitHub server or plugin went something wrong, does `http://kagerou.hibiya.moe/overlay` work?

**Comment by Kou4444** [comment]
it works now ty
