### ISSUE TITLE
Error when loading in ACT

### ISSUE THREAD

**Issue by dlevine3** [hibiyasleep/kagerou#65]
mini parse: BrowserConsol: UncaughtTypeError: undefined is not a function(Source:https://hibiyasleep.github.io/Kagerou/outdated/.Line:87)

Using 3.3.1.255 ACT 
All browsers up to date.
![kagerou failed to start](https://user-images.githubusercontent.com/5386376/29855809-dc2c4e90-8d0b-11e7-890c-da1e8f312442.jpg)

**Comment by hibiyasleep** [comment]
Please update your OverlayPlugin as explained on overlay, download is available from [here](https://github.com/hibiyasleep/OverlayPlugin/releases/).
