### ISSUE TITLE
Request: black outline for text in parse window

### ISSUE THREAD

**Issue by brandonho36** [hibiyasleep/kagerou#68]
Hey, I really like this overlay! I just wish there was a way to have a black outline around all the text, because I use a background image that has some white and the text is unreadable on those parts. 

Image here: https://i.imgur.com/BRIyQYG.png 
the right columns are unreadable

**Comment by hibiyasleep** [comment]
There's some possible way to make those text readable:

1. make shadow stronger - At settings > style > shadow > text, set `0 0 0.25em rgba(0, 0, 0, 1), 0 0 0.25em rgba(0, 0, 0, 1)` will look like this:
![2017-09-07 11 10 16](https://user-images.githubusercontent.com/5380174/30142693-2a261e98-93bd-11e7-8937-820367dc9d88.png)

2. make your image darker with opacity option or/and 'CSS filter'; `brightness(0.7)` will make image dark enough (I think).
