### ISSUE TITLE
Overlay won't load

### ISSUE THREAD

**Issue by ultimatequix** [hibiyasleep/kagerou#72]
I've had ACT installed and working for some time now, and have reinstalled both ACT and the FFXIV plugin. The problem I'm having is that as soon as I paste in the URL to kagerou and load the overlay, I get the following message in the overlay:

kagerou failed to start
Your browser is outdated or not supported. Scroll down for more info.

Why this happened?
Current browser doesn't support some features that kagerou requires. This may happen if you're in 'incognito' mode.

What can I do?
OverlayPlugin
please update your plugin, kagerou requires v0.3.3.10 or newer.

etc etc etc

I'm currently using 0.3.3.12 and 0.3.3.14 overlays and both give me the same error. I'm not sure what it means by incorrect browser, as I'm using a current version of chrome and not in incognito. If anyone could help that'd be great.

**Comment by hibiyasleep** [comment]
1. `Open DevTools`
2. click `Console`
3. paste this then enter:
```js
new Function('a', "'use strict'; const b=(_=>`${_}`)(a); return b")(1)
```

This should display `"1"`, please report if there's any errors or not.

**Comment by huyhuy212** [comment]
[](https://www.img.in.th/images/8ed521544b9a482ed8caa35ed856357a.jpg)

what happened ??

**Comment by ultimatequix** [comment]
@huyhuy212 It was a win10 issue. I redownloaded ACT, opened the installer's properties and unblocked it, then ran ACT as admin after it was installed.
