### ISSUE TITLE
kagerou overlay don't appear

### ISSUE THREAD

**Issue by poltergiestRysk** [hibiyasleep/kagerou#73]
Error Mini Parse BrowserError: - 130, , https://hibiyasleep.github.io/kagerou/overlay

^ i get this message on ACT plug in tab on OverlayPlugin.dll

I've already reinstalled ACT and re-downloaded FFXIV_ACT_Plugin.dll and OverlayPlugin.dll
dunno how to fix this one please help

**Comment by hibiyasleep** [comment]
It means 'Cannot connect to configured proxy server', please follow [this guide](https://productforums.google.com/forum/#!topic/chrome/8OBy1xe1VHY) to disable or reconfigure the proxy.

**Comment by poltergiestRysk** [comment]
it worked thanks so much!
