### ISSUE TITLE
Cannot Load OverlayPlugin.dll in ACT

### ISSUE THREAD

**Issue by Jekt729** [hibiyasleep/kagerou#74]
I receive an error when trying to load Overylayplugin.dll, when I add it the first time I get this error, 

![image](https://user-images.githubusercontent.com/32624099/31322318-8b7739de-ac63-11e7-8540-375a64e01703.png)

When I attempt to do a second time, plus every subsequent time until ACT is exited and restarted, I get this error,

![image](https://user-images.githubusercontent.com/32624099/31322329-bad35924-ac63-11e7-930b-9816f518a6bc.png)

I'm running windows 10 with .NET framework version 4.7 with OverlayPlugin-0.3.3.12-x64-full. Any advice on how to get this working would be much appreciated!

**Comment by hibiyasleep** [comment]
didn't you forget `Unlock` All DLL files, before `add/enable plugin`?

**Comment by Jekt729** [comment]
I extracted the latest version of the overlay zip from your download section to a new folder in ACT directory. In ACT > PlugIns Tab > PlugIn Listing > Browse > Selected OverlayPlug.dll file > Add/Enable and checked off the box to enable. That’s when it threw me those errors.

**Comment by Jekt729** [comment]
When you say unlock, do you mean extract from the zip file or is there some that are locked with a password?

**Comment by Jekt729** [comment]
Screen shot of my directory.

![image](https://user-images.githubusercontent.com/32624099/31360059-a5050d4c-ad1a-11e7-8440-44fdf0312f48.png)
