### ISSUE TITLE
Patch 4.1

### ISSUE THREAD

**Issue by deadvenger** [hibiyasleep/kagerou#75]
I know the patch just hit but I prefer letting you know of a possible issue regardless.
Since 4.1 : https://gyazo.com/5efdbcf81736881485d6f419297412f5

Names and numbers are not showing. Re-installed everything and nothing changed. Ohter overlay works just fine.

**Comment by hibiyasleep** [comment]
I can't test just right now, can you attach a capture of `Open DevTools > Console` after this occurs?

**Comment by deadvenger** [comment]
https://gyazo.com/f5c863b1757c0431a9148b7184f7b044

**Comment by hibiyasleep** [comment]
🤔 nothing changed from overlay's sight, there's no another errors?

**Comment by insomxd** [comment]
also have the same issue, no names of players and individual numbers are showing, however total dps still shows in bottom right corner http://puu.sh/xWnkT/0808f4d351.png

**Comment by hibiyasleep** [comment]
no any error log at this moment, right? it's curious...

**Comment by PipoPassword** [comment]
I am having the same issue as well, reinstalled and everything. https://i.imgur.com/mvXY2rF.png

**Comment by hibiyasleep** [comment]
I can't reproduce this error, even nothing reported on error tracker. please capture your `Console` (in devtools) after occur, without refreshing.

**Comment by brandonho36** [comment]
I get this error too

10/12/2017 8:24:24 PM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin
10/12/2017 8:24:24 PM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\EnmityOverlay.dll
10/12/2017 8:24:42 PM: Info: LoadAddons: Tamagawa.EnmityPlugin.OverlayAddonMain: Initialized
10/12/2017 8:24:44 PM: Error: Enmity Overlay: Failed to signature scan (charmapAddress).
10/12/2017 8:24:44 PM: Info: InitPlugin: Initialized.
10/12/2017 8:24:47 PM: Info: Mini Parse: BrowserConsole: Mixed Content: The page at 'https://hibiyasleep.github.io/kagerou/overlay/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/IzVGALe.jpg'. This content should also be served over HTTPS. (Source: https://hibiyasleep.github.io/kagerou/overlay/, Line: 0)

What's weird is that Limit Break shows up in the parser overlay, Just nothing else

**Comment by insomxd** [comment]
http://puu.sh/xWVl3/908b7c5648.jpg

**Comment by insomxd** [comment]
just checked Plugins > FFXIV Settings > Parser Messages and I have this as an error as well,

ERROR: Unable to find Signature for [PartyList].
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]

The error just repeats, does anyone else get this issue?

**Comment by hibiyasleep** [comment]
oh well, it's FFXIV_ACT_Plugin's issue, which failing to determine who's party or not.

First, try update FFXIV_ACT_Plugin (now 1.5.1.9), or at `ACT > Plugins > FFXIV_ACT_Plugin`:

![2017-10-13 15 09 44](https://user-images.githubusercontent.com/5380174/31532486-946d689c-b028-11e7-87d4-143635ac74b1.png)

This worked for me at least, please try this.

**Comment by insomxd** [comment]
Yup tried that, still getting same error.

**Comment by hibiyasleep** [comment]
Can you post a text copied from `Copy the update variable to clipboard`?

**Comment by insomxd** [comment]
{
  "Encounter": {
    "n": "\n",
    "t": "\t",
    "title": "Encounter",
    "duration": "00:42",
    "DURATION": "42",
    "damage": "0",
    "damage-m": "0.00",
    "DAMAGE-k": "0",
    "DAMAGE-m": "0",
    "DAMAGE-b": "0",
    "dps": "0.00",
    "DPS": "0",
    "DPS-k": "0",
    "DPS-m": "DPS-m",
    "encdps": "0.00",
    "ENCDPS": "0",
    "ENCDPS-k": "0",
    "ENCDPS-m": "0",
    "hits": "0",
    "crithits": "0",
    "crithit%": "NaN",
    "misses": "0",
    "hitfailed": "0",
    "swings": "0",
    "tohit": "NaN",
    "TOHIT": "NaN",
    "maxhit": "",
    "MAXHIT": "",
    "healed": "0",
    "enchps": "0.00",
    "ENCHPS": "0",
    "ENCHPS-k": "0",
    "ENCHPS-m": "0",
    "heals": "0",
    "critheals": "0",
    "critheal%": "NaN",
    "cures": "0",
    "maxheal": "",
    "MAXHEAL": "",
    "maxhealward": "",
    "MAXHEALWARD": "",
    "damagetaken": "0",
    "healstaken": "0",
    "powerdrain": "0",
    "powerheal": "0",
    "kills": "0",
    "deaths": "0",
    "CurrentZoneName": "Central Thanalan",
    "Last10DPS": "0",
    "Last30DPS": "0",
    "Last60DPS": "0"
  },
  "Combatant": {},
  "isActive": "false"
}

**Comment by insomxd** [comment]
{
  "Encounter": {
    "n": "\n",
    "t": "\t",
    "title": "Encounter",
    "duration": "00:03",
    "DURATION": "3",
    "damage": "11299",
    "damage-m": "0.01",
    "DAMAGE-k": "11",
    "DAMAGE-m": "0",
    "DAMAGE-b": "0",
    "dps": "3766.33",
    "DPS": "3766",
    "DPS-k": "4",
    "DPS-m": "DPS-m",
    "encdps": "3766.33",
    "ENCDPS": "3766",
    "ENCDPS-k": "4",
    "ENCDPS-m": "0",
    "hits": "4",
    "crithits": "1",
    "crithit%": "0%",
    "misses": "0",
    "hitfailed": "0",
    "swings": "4",
    "tohit": "100.00",
    "TOHIT": "100",
    "maxhit": "YOU-Shifu-4,394",
    "MAXHIT": "YOU-4,394",
    "healed": "0",
    "enchps": "0.00",
    "ENCHPS": "0",
    "ENCHPS-k": "0",
    "ENCHPS-m": "0",
    "heals": "0",
    "critheals": "1",
    "critheal%": "NaN",
    "cures": "0",
    "maxheal": "",
    "MAXHEAL": "",
    "maxhealward": "",
    "MAXHEALWARD": "",
    "damagetaken": "0",
    "healstaken": "0",
    "powerdrain": "0",
    "powerheal": "0",
    "kills": "0",
    "deaths": "0",
    "CurrentZoneName": "Mist",
    "Last10DPS": "3766",
    "Last30DPS": "3766",
    "Last60DPS": "3766"
  },
  "Combatant": {
    "YOU": {
      "n": "\n",
      "t": "\t",
      "name": "YOU",
      "duration": "00:03",
      "DURATION": "3",
      "damage": "11299",
      "damage-m": "0.01",
      "damage-b": "0.00",
      "DAMAGE-k": "11",
      "DAMAGE-m": "0",
      "DAMAGE-b": "0",
      "damage%": "100%",
      "dps": "3766.33",
      "DPS": "3766",
      "DPS-k": "4",
      "DPS-m": "0",
      "encdps": "3766.33",
      "ENCDPS": "3766",
      "ENCDPS-k": "4",
      "ENCDPS-m": "0",
      "hits": "4",
      "crithits": "1",
      "crithit%": "25%",
      "crittypes": "0.0%L - 0.0%F - 0.0%M",
      "misses": "0",
      "hitfailed": "0",
      "swings": "4",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Shifu-4,394",
      "MAXHIT": "4,394",
      "healed": "0",
      "healed%": "--",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "ENCHPS-m": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "0",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "0",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "YOU",
      "NAME4": "YOU",
      "NAME5": "YOU",
      "NAME6": "YOU",
      "NAME7": "YOU",
      "NAME8": "YOU",
      "NAME9": "YOU",
      "NAME10": "YOU",
      "NAME11": "YOU",
      "NAME12": "YOU",
      "NAME13": "YOU",
      "NAME14": "YOU",
      "NAME15": "YOU",
      "Last10DPS": "3766",
      "Last30DPS": "3766",
      "Last60DPS": "3766",
      "Job": "",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "---",
      "OverHealPct": "0%",
      "DirectHitPct": "50%",
      "DirectHitCount": "2",
      "CritDirectHitCount": "0",
      "CritDirectHitPct": "0%"
    }
  },
  "isActive": "true"
}

**Comment by hibiyasleep** [comment]
**Reason**: FFXIV_ACT_Plugin **doesn't** assign for (unknown) some reason or bug, so kagerou filtered it out because empty job is almostly means unnecessary enemies.

**Workaround**: Settings > More > Others, disable `Class/Job is empty` option.

or try start game as DX11, FFXIV_ACT_Plugin always better on it.

**Comment by insomxd** [comment]
Thanks Hibiya

**Comment by hibiyasleep** [comment]
![2017-10-13 19 07 26](https://user-images.githubusercontent.com/5380174/31541489-c8e6202a-b049-11e7-9c35-b7977f3135ce.png)

v0.7.15 updated - You can simply click this button to apply workaround shown above.

**Comment by deadvenger** [comment]
Will try all of this once I have some time (probably late tonight/early tomorow). Will post update.

**Comment by hibiyasleep** [comment]
Real peoblem was DX9 - currently latest FFXIV_ACT_Plugin doesn't support DX9, so please switch to DX11 until supporting update announced.

**Comment by deadvenger** [comment]
Was working out a way to make it work but...the most recent patch made it so it's working now...so....Yeah, issue solved Xd
