### ISSUE TITLE
No job Icons 

### ISSUE THREAD

**Issue by Mioojo1812** [hibiyasleep/kagerou#76]
![parserbug](https://user-images.githubusercontent.com/32792432/31574832-4780c9b2-b0ae-11e7-9dbe-9e70d8954ea5.jpg)
I might be missing something but i cant see  the job icons on my parse.

**Comment by hibiyasleep** [comment]
currently latest FFXIV_ACT_Plugin doesn't support DX9, so please switch to DX11 until supporting update announced. See also: #75
