### ISSUE TITLE
Initialize Lastname support

### ISSUE THREAD

**Issue by Hoshiyuu** [hibiyasleep/kagerou#8]
(Apologies for opening an issue ticket for feature request)
Could there also be an option to initializing lastname?

Firstname Lastname
F. Lastname (We have this)
First L. (I would love this)

Thank you.

**Comment by hibiyasleep** [comment]
That's not problem, suggestion is one of what issue trackers do! It'll added on next version.

**Comment by hibiyasleep** [comment]
![image](https://cloud.githubusercontent.com/assets/5380174/22172525/93924814-dfec-11e6-9d23-c181c0abfde1.png)

Added by v0.5.7; You can change anyway you want.
