### ISSUE TITLE
Background image url wont work

### ISSUE THREAD

**Issue by finHards** [hibiyasleep/kagerou#82]
I'm trying to get the background image url to work even using ('url') however nothing happens

**Comment by hibiyasleep** [comment]
it should look like: `url('http://foo.bar/ham/spam.png')`, starting with `url(` and then URL, then closing `)`.

**Comment by finHards** [comment]
thanks for the reply, is it also possible to make the text values black
instead of white like the dps values etc?

thanks

**Comment by hibiyasleep** [comment]
Adjust color of `Style > Foreground > Table`, #111 for value just enough.
