### ISSUE TITLE
Browser error

### ISSUE THREAD

**Issue by auggeris** [hibiyasleep/kagerou#86]
overlay no longer showing getting Error:/12/2017 14:45:31: Error: overlay: BrowserError: -330, , https://hibiyasleep.github.io/kagerou/overlay/

**Comment by auggeris** [comment]
fixed by changing url to http://kagerou.hibiya.moe/overlay

**Comment by hibiyasleep** [comment]
`-330` means Chromium error code `ERR_CONTENT_DECODING_FAILED`, however it's curious `hibiyasleep.github.io` is managed by GitHub... anyway thanks for report!
