### ISSUE TITLE
Overlay stopped registering combat

### ISSUE THREAD

**Issue by Flip888** [hibiyasleep/kagerou#87]
My mini parser stopped registering damage. ACT itself will show the log but the overlay simply says "awaiting combat". Please see the errors returned on the image attached.

![kkkkkkkkkkkkkkkkkkk](https://user-images.githubusercontent.com/34406142/33800218-98862332-dd33-11e7-806c-4e9a349861bc.PNG)

**Comment by Andrycism** [comment]
Network error I guess. Try to check your internet connection than refresh overlay

**Comment by Flip888** [comment]
Hello. I've restarted everything multiple times, and this is the only problem I'm having, everything else works fine.

I've now tried to use the parser that we have installed locally (image below) and it works fine. It's only when I replace it with the URL "https://hibiyasleep.github.io/kagerou/overlay" that the mini parser will just say "Awaiting combat", despite SCT itself registering damage. 

![image](https://user-images.githubusercontent.com/34406142/33800388-e24a801e-dd36-11e7-89a7-9aad09b11350.png)

It also says "Unsecure mode over http" but I never really paid attention so dont know if that's normal.

![image](https://user-images.githubusercontent.com/34406142/33805604-9626a654-ddb3-11e7-92d1-798ff3cf9494.png)

**Comment by Flip888** [comment]
Sorry, still open. Any ideas?

**Comment by hibiyasleep** [comment]
Seems Something getting wrong on GitHub's web server, please try replace URL with `http://kagerou.hibiya.moe/overlay`. - and "UNSECURE MODE" alert is normal, indicating it's not on HTTPS for some reason.

**Comment by hibiyasleep** [comment]
P.S. for error logs: [ws-abstract.js:163](https://github.com/hibiyasleep/kagerou/blob/master/share/lib/ws-abstract.js#L163) is empty line and is (usually) nothing to cause errors... I'm guessing it's network error with GitHub server.

**Comment by Flip888** [comment]
The new URL fixed it. I'll just keep that one unless there is any advantage to use the original link, in which case I can try again later. Thanks a lot, I made a small contribution for your help.
