### ISSUE TITLE
Overlay not starting the right way

### ISSUE THREAD

**Issue by TheSprent** [hibiyasleep/kagerou#89]
kagerou failed to start, my main brower is ff and i get this error 05.02.2018 22.02.12: Info: Totoro: BrowserConsole: Uncaught ReferenceError: len is not defined (Source: https://hibiyasleep.github.io/kagerou/outdated/, Line: 86)
 and i am using this link https://hibiyasleep.github.io/kagerou/overlay/
 and the overlayplugin is 3.4.0

**Comment by hibiyasleep** [comment]
please try this URL: `https://hibiyasleep.github.io/kagerou/overlay/#ignore-feature-test`

This will make 'skip' feature test that sometimes causes a problem.

**Comment by TheSprent** [comment]
that changes the overlay from failed to start to failes to load-

 and the error messages alot more : 06.02.2018 16.04.45: Info: Totoro: BrowserConsole: Uncaught SyntaxError: Use of const in strict mode. (Source: https://hibiyasleep.github.io/kagerou/share/lib/util.js?v=never-lost-word, Line: 3)
06.02.2018 16.04.45: Info: Totoro: BrowserConsole: Uncaught SyntaxError: Use of const in strict mode. (Source: https://hibiyasleep.github.io/kagerou/share/lib/config.js?v=never-lost-word, Line: 3)
06.02.2018 16.04.45: Info: Totoro: BrowserConsole: Uncaught ReferenceError: VERSION is not defined (Source: https://hibiyasleep.github.io/kagerou/overlay/, Line: 45)
06.02.2018 16.04.45: Info: Totoro: BrowserConsole: Uncaught SyntaxError: Use of const in strict mode. (Source: https://hibiyasleep.github.io/kagerou/overlay/lib/listen.js?v=never-lost-word, Line: 5)
06.02.2018 16.04.45: Info: Totoro: BrowserConsole: Uncaught SyntaxError: Unexpected reserved word (Source: https://hibiyasleep.github.io/kagerou/overlay/lib/ui.js?v=never-lost-word, Line: 5)
06.02.2018 16.04.45: Info: Totoro: BrowserConsole: Uncaught SyntaxError: Unexpected token => (Source: https://hibiyasleep.github.io/kagerou/overlay/, Line: 74)
 there was a some more lines of the same line 5 error
![failed to load](https://user-images.githubusercontent.com/36173163/35866663-18045352-0b58-11e8-95ca-23fbf5e0a944.PNG)
![error](https://user-images.githubusercontent.com/36173163/35866677-1ce1190a-0b58-11e8-919b-72c696ab1680.PNG)

and 2 pictures on on the overlay if i try pressing settings or  retry it crashes ACT

**Comment by hibiyasleep** [comment]
it seems you are using overlayplugin 0.3.3.9 or something (as seen from screenshot), please try re-install OverlayPlugin from [here](https://github.com/hibiyasleep/OverlayPlugin/releases/latest).

**Comment by TheSprent** [comment]
i reinstalled act it self and now it works fine  since i tried removing overlay by removing the folder noting changed reinstalled act completly and  it works fine now

**Comment by hibiyasleep** [comment]
:+1:
