### ISSUE TITLE
Overlay not outputting anything

### ISSUE THREAD

**Issue by Communist-Weeaboo** [hibiyasleep/kagerou#90]
I had the parse plugin working until the patch last week, but now I have yet to get any data, neither in the overlay nor the actual application. Is anyone else getting this, or is mine just broken?

**Comment by hibiyasleep** [comment]
You need to [update FFXIV_ACT_Plugin](https://github.com/ravahn/FFXIV_ACT_Plugin/releases) every time after major patch happens.
