### ISSUE TITLE
Object Reference Error when clicking 'reload overloay'

### ISSUE THREAD

**Issue by nykspree8** [hibiyasleep/kagerou#94]
Hi, i'm gettting the following error message - please help :) 
![image](https://user-images.githubusercontent.com/39626887/40549936-c5cac716-6006-11e8-85f9-cdc8cf033ad3.png)

**Comment by nykspree8** [comment]
Hi, can anyone please help with this?

**Comment by dragonflyysoftware** [comment]
I'm getting that error whenever I make any changes to the plugin. Also it is not creating the config file in %appdata%.

Running ACT as admin.

**Comment by hibiyasleep** [comment]
This is problem of OverlayPlugin, and reason is so vary. sorry ;(
