### ISSUE TITLE
정보 수집

### ISSUE THREAD

**Issue by ffxivvillein** [hibiyasleep/kagerou#98]
http://www.inven.co.kr/board/ff14/4336/698852

여기 보면 오버레이 사용시 전투집계에 대한 정보를 수집하는거 같은데 어떻게 해제하나요?

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/43253394-d5593a1c-90ff-11e8-8e47-957fdffc821b.png)

제 로그입니다.
