### ISSUE TITLE
Getting an error. Overlay not displaying

### ISSUE THREAD

**Issue by Draconlifors** [hibiyasleep/kagerou#99]
The overlay was working fine for about 3 hours, then when I went to reload the overlay in prep for a new pull, it disappeared and I get the following error

8/4/2018 11:07:38 PM: Error: Kage: BrowserError: -330, , https://hibiyasleep.github.io/kagerou/overlay/

I then tried to open the link in my browser to see if the link went bad or something and it worked fine in my browser, dont know whats wrong

**Comment by Draconlifors** [comment]
And it just randomly fixed itself..

**Comment by ZeburaBlack** [comment]
I am also getting this error, randomly stopped working with the exact error
no idea how to fix it, google has been of zero help

**Comment by hibiyasleep** [comment]
Error -330 is `ERR_CONTENT_DECODING_FAILED`, and it means *server* sent something wrong and/or *browser* failed to interpret it. try [ngld version of overlayplugin](https://github.com/ngld/overlayplugin/releases), it has newer chromium version and should work as normal.
